# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fluent-plugin-scribe}
  s.version = "0.9.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kazuki Ohta"]
  s.date = %q{2011-08-06}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "AUTHORS",
    "Rakefile",
    "VERSION",
    "example.conf",
    "fluent-plugin-scribe.gemspec",
    "lib/fluent/plugin/out_tdlog.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Scribe plugin for Fluent event collector}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thrift>, [">= 0.7.0"])
      s.add_runtime_dependency(%q<fluent>, ["~> 0.9.7"])
    else
      s.add_dependency(%q<thrift>, [">= 0.7.0"])
      s.add_dependency(%q<fluent>, ["~> 0.9.7"])
    end
  else
    s.add_dependency(%q<thrift>, [">= 0.7.0"])
    s.add_dependency(%q<fluent>, ["~> 0.9.7"])
  end
end

